/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.xl350.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
    
    private final TextPlayer p1;
    private final TextPlayer p2;
    
    /**
     * @param p1 player1
     * @param p2 player2
     */
    public App(TextPlayer p1,TextPlayer p2){
        this.p1 = p1;
        this.p2 = p2;
    }
    
    public void doPlacementPhase()throws IOException{
        p1.doPlacementPhase();
        p2.doPlacementPhase();
    }

    public void doAttackingPhase() throws IOException{
        while(true){
            p1.playOneTurn(p2.theBoard,p2.view,p2.name);
            if(p2.ifLost()){
                p1.printWin();
                break;
            }
            p2.playOneTurn(p1.theBoard,p1.view,p1.name);
            if(p1.ifLost()){
                p2.printWin();
                break;
            }
        }
    }

    /**
     * construct an app object and try to add a ship to it.
     */
    public static void main(String[] args) throws IOException{
        Board<Character> b1 = new BattleShipBoard<Character>(10, 20,'X');
        Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));        
        V2ShipFactory factory = new V2ShipFactory();
        PrintStream out = System.out;
        TextPlayer p1 = new TextPlayer("A", b1, input, out, factory);
        TextPlayer p2 = new TextPlayer("B", b2, input, out, factory);
        App app = new App(p1,p2);
        app.doPlacementPhase();
        app.doAttackingPhase();
    }
}









